import re

character_mapping = {
    'á': 'a',
    'à': 'a',
    'â': 'a',
    'ä': 'a',
    'ã': 'a',
    'å': 'a',
    'æ': 'ae',
    'ç': 'c',
    'č': 'c',
    "ć": "c",
    'é': 'e',
    "É": "E",
    'è': 'e',
    'ê': 'e',
    'ë': 'e',
    "ė": "e",
    'í': 'i',
    'ì': 'i',
    'î': 'i',
    'ï': 'i',
    'ñ': 'n',
    'ó': 'o',
    'ò': 'o',
    'ô': 'o',
    'ö': 'o',
    'õ': 'o',
    'ø': 'o',
    'œ': 'oe',
    'š': 's',
    "ß": "ss",
    'ú': 'u',
    'ù': 'u',
    'û': 'u',
    'ü': 'u',
    'ý': 'y',
    'ÿ': 'y',
    'ž': 'z',
    
    # Add uppercase letters as well
    'Á': 'A',
    'À': 'A',
    'Â': 'A',
    'Ä': 'A',
    'Ã': 'A',
    'Å': 'A',
    'Æ': 'AE',
    'Ç': 'C',
    'Č': 'C',
    "Ć": "C",
    'É': 'E',
    'È': 'E',
    'Ê': 'E',
    'Ë': 'E',
    "Ė": "E",
    'Í': 'I',
    'Ì': 'I',
    'Î': 'I',
    'Ï': 'I',
    'Ñ': 'N',
    'Ó': 'O',
    'Ò': 'O',
    'Ô': 'O',
    'Ö': 'O',
    'Õ': 'O',
    'Ø': 'O',
    'Œ': 'OE',
    'Š': 'S',
    'Ú': 'U',
    'Ù': 'U',
    'Û': 'U',
    'Ü': 'U',
    'Ý': 'Y',
    'Ÿ': 'Y',
    'Ž': 'Z',

    # Additional non-standard characters
    'æ': 'ae',
    'Æ': 'AE',
    'œ': 'oe',
    'Œ': 'OE',
    'ß': 'ss',
    'Þ': 'th',
    'þ': 'th',
    'ð': 'dh',
    'Đ': 'D',
    'đ': 'd',
    'ł': 'l',
    'Ł': 'L',
    'đ': 'd',
    'Đ': 'D',
    'ß': 'ss',
    'Þ': 'th',
    'þ': 'th',
    'ð': 'dh',
    'Æ': 'AE',
    'œ': 'oe',
    'ß': 'ss',
    'Ø': 'O',
    'ø': 'o',
    'Å': 'A',
    'å': 'a',
}

def transform_to_swift_accepted_characters(input_list):
    transformed_list = []
    for input_string in input_list:
        transformed_string = re.sub(r'\b\w+\b', lambda m: ''.join(character_mapping.get(char, char) for char in m.group()), str(input_string))
        transformed_string = re.sub(r'[.,]', '', transformed_string)  # Remove dots and commas
        transformed_list.append(transformed_string)
    return transformed_list